version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:5000/api
    command: npm run dev

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_URI=mongodb://db:27017/peta_ilmu_islam
      - JWT_SECRET=super_rahasia
    command: npm run dev

  db:
    image: mongo:7.0-jammy
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: